epochs: 10
lr: 0.00001
lr_scheduler: cosine_change_per_epoch
optim: adam
wd: 1e-06
bs: 16
input_size: (512, 512)

sampler: RandomSampler
model_name: resnet50
drop_out_rate: 0.2
freeze_bn_epochs: 0
accum_iter: 1
loss_func: TaylorCrossEntropyLoss
label_smooth_epsilon : 0.05 
fp16: True
do_mixup_in_dataset: 0
do_cutmix_in_dataset: 0
do_cutmix_in_batch: 0.5

dataset: '/data/nextcloud/dbc2017/files/images'


