dataset:
  type: dir
  name: ImageNet
  dataset_dir: '/data/nextcloud/dbc2017/files/images'
  image_size: 224
  n_channels: 3
  n_classes: 50
model:
  type: imagenet
  name: resnet34
  pretrain: True
  pretrain_pth: 'pretrain_models/resnet34-333f7ec4.pth'
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: True
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
tta:
  use_resize: True
  use_center_crop: True
  resize: 256
train:
  output_dir: experiments/imagenet/resnet34/exp01
  use_apex: False
  batch_size: 8
validation:
  batch_size: 8

