dataset:
  type: df
  name: ImageNet
  subname: K100
  dataset_dir: '/content/images'
  image_size: 224
  n_channels: 3
  n_classes: 10
  cvsfile_train: '/content/MultitaskPainting100k_Dataset_groundtruth/groundtruth_multiloss_train_header.csv'
  cvsfile_test: '/content/MultitaskPainting100k_Dataset_groundtruth/groundtruth_multiloss_test_header.csv'
model:
  type: imagenet
  name: efficientnet-b5
  pretrain: True
  pretrain_pth: None
  multitask: True
augmentation:
  use_albumentations: False
  use_random_crop: True
  use_random_horizontal_flip: True
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
tta:
  use_resize: True
  use_center_crop: True
  resize: 256
scheduler:
  type: 'CosineAnnealing'
  lr_min_factor: 1e-6
  epochs: 10
  T0: 10
train:
  output_dir: experiments/K100/efficientnet-b5/exp01
  use_apex: False
  batch_size: 32
  seed: 123
  use_kfold: False
  fold_num: 5
  base_lr: 3e-4
  weight_decay: 1e-6
  optimizer: 'admw'
  dataloader:
    num_workers: 8
validation:
  batch_size: 32
  dataloader:
    num_workers: 8
test:
  batch_size: 32
  dataloader:
    pin_memory: False
    num_workers: 8
  checkpoint: 'experiments/imagenet/efficientnet-b5/exp01'
  output_dir: 'outputs/imagenet/efficientnet-b5/exp01'

