dataset:
  type: df
  name: ImageNet
  cvsfile_train: '/content/train.csv'
  cvsfile_test: None
  jsonfile: None
  dataset_dir: '/content' #root_dir
  image_size: 224
  n_channels: 3
  n_classes: 176
model:
  type: imagenet
  name: efficientnet-b0
  pretrain: True
  pretrain_pth: None
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: True
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
tta:
  use_resize: True
  use_center_crop: True
  resize: 256
train:
  output_dir: experiments/imagenet/efficientnet-b0/exp00
  use_apex: False
  batch_size: 8
scheduler:
  epochs: 20
  type: multistep
  milestones: [10, 20]
  lr_decay: 0.0001
validation:
  batch_size: 8

